{
 "title": "Nginx",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Active connections",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "nginx_connections_active" }
   ]
  },
  {
   "title": "Active connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nginx_connections_reading", "legendFormat": "reading" },
    { "expr": "nginx_connections_writing", "legendFormat": "writing" },
    { "expr": "nginx_connections_waiting", "legendFormat": "waiting" }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total[30s])"
    }
   ]
  },
  {
   "title": "Accepted & Handled connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(nginx_connections_accepted[30s])",
     "legendFormat": "accepted"
    },
    {
     "expr": "rate(nginx_connections_handled[30s])",
     "legendFormat": "handled"
    }
   ]
  }
 ]
}